-- Wuzzify v5 CMS — initial schema (MySQL 8+)
-- Run this against your MySQL database when DB_SYNC is not enabled.
-- IDs are CHAR(36) UUIDs generated by the application (TypeORM).

-- Admins ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id            CHAR(36)     NOT NULL,
  email         VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name          VARCHAR(255) NULL,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_admins_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Articles --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS articles (
  id           CHAR(36)     NOT NULL,
  slug         VARCHAR(255) NOT NULL,
  title_ar     VARCHAR(300) NOT NULL,
  title_en     VARCHAR(300) NULL,
  excerpt_ar   TEXT         NULL,
  excerpt_en   TEXT         NULL,
  content_ar   LONGTEXT     NOT NULL,
  content_en   LONGTEXT     NULL,
  cover_url    VARCHAR(1024) NULL,
  status       ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME(6)  NULL,
  created_at   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_articles_slug (slug),
  KEY idx_articles_status_published_at (status, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
